[source]
paths = ["src"]
excludes = [ ]
includes = ["vendor"]
extensions = ["php", "php81"]

[linter]
level = "Error"

[[linter.rules]]
name = "best-practices/no-unused-parameter"
level = "Off"

[[linter.rules]]
name = "best-practices/loop-does-not-iterate"
level = "Off"

[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "Off"

[[linter.rules]]
name = "strictness/require-constant-type"
level = "Off"

[[linter.rules]]
name = "strictness/missing-assert-description"
level = "Off"

[[linter.rules]]
name = "safety/no-suppressed-expression"
level = "Off"

[[linter.rules]]
name = "comment/docblock-syntax"
level = "Note"

[[linter.rules]]
name = "deprecation/optional-parameter-before-required"
level = "Off"

[[linter.rules]]
name = "best-practices/no-multi-assignments"
level = "Off"

[[linter.rules]]
name = "migration/readonly-class-promotion"
level = "Off"
