php_version = "8.1"

[source]
paths = ["src"]
excludes = [ ]
includes = ["vendor"]
extensions = ["php"]

[linter]
default_plugins = true

[[linter.rules]]
name = "best-practices/no-unused-parameter"
level = "Off"

[[linter.rules]]
name = "best-practices/loop-does-not-iterate"
level = "Off"

[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "Off"

[[linter.rules]]
name = "strictness/missing-assert-description"
level = "Off"

[[linter.rules]]
name = "safety/no-suppressed-expression"
level = "Off"

[[linter.rules]]
name = "comment/docblock-syntax"
level = "Note"

[[linter.rules]]
name = "deprecation/optional-parameter-before-required"
level = "Off"

[[linter.rules]]
name = "best-practices/no-multi-assignments"
level = "Off"

[[linter.rules]]
name = "maintainability/kan-defect"
level = "Off"

[[linter.rules]]
name = "maintainability/halstead"
level = "Off"

[[linter.rules]]
name = "maintainability/cyclomatic-complexity"
level = "Off"

[[linter.rules]]
name = "maintainability/too-many-methods"
level = "Off"

[[linter.rules]]
name = "maintainability/excessive-parameter-list"
level = "Off"

[[linter.rules]]
name = "maintainability/too-many-properties"
level = "Off"

[[linter.rules]]
name = "maintainability/too-many-enum-cases"
level = "Off"
